public/js/app/models/Post.js, public/js/app/templates/_postTemplate.handlebars, public/js/app/views/PartialPostView.js, public/js/locales/default.js
Fixes #24 
With minor deficiency from FRF:
- After Un-liking the showAllLikes is not reset to false as it should.
Potential improvement:
- Current user's like can be put always first, see commented code.
=> Folded likes

public/js/app/templates/postTemplate.handlebars
This fixes showing of comment list and adding new ones on one-post page
(like, http://freefeed.net/#/clbn/c6d1a81d-1b79-4f62-a49c-1189a11d7768)
=> Fix comments display and creation on one-post page

public/js/app/controllers/PostController.js
This is going to happen another time unless we extract actions to
TimelinePostGenericController that will be a parent controller for
TimelinePostController and PostController controllers.
=> Fixes regression when user is not able to add a comment on one post view

public/js/app/main.js, public/js/app/models/Subscriber.js
page.
Restores Subscriber model for the time being and so fixes /subscribes
page. Fixes #188
=> Restores Subscriber model for the time being and so fixes /subscribes

public/js/app/controllers/PostCommentController.js, public/js/app/controllers/PostController.js, public/js/app/controllers/TimelinePostController.js, public/js/app/templates/postCommentTemplate.handlebars, public/js/app/templates/postTemplate.handlebars, public/js/app/templates/timelinePostTemplate.handlebars, public/js/app/views/PostCommentView.js, public/js/app/views/PostView.js, public/js/app/views/TimelinePostView.js
Moves isEdit property from view to controller so we can manage it on
action "update" and toggle editing mode if post has been saved.
=> Moves isEdit property from view to controller that fixes #190.

public/js/app/components/Pagination.js, public/js/app/templates/timelineDiscussionsTemplate.handlebars, public/js/app/templates/timelineHomeTemplate.handlebars, public/js/app/templates/timelineIndexTemplate.handlebars
Does not show submit field post on 2+ pages on Home, Group/User and My
Discussions feeds.
=> Does not show submit post on 2+ pages on some feeds. Fixes #180.

public/js/app/templates/profileLinksTemplate.handlebars, public/js/app/views/ProfileLinksView.js
=> Make "profile-links" aware of current user

public/js/app/controllers/TimelineDiscussionsController.js, public/js/app/controllers/TimelineHomeController.js, public/js/app/templates/sendToTemplate.handlebars
Functional implementation of #177 and #140. Requires styling though. Found a defect in backend: https://github.com/pepyatka/pepyatka-server/issues/164
=> Allows to submit a post to 2+ feeds.

public/js/app/controllers/SessionNewController.js, public/js/app/controllers/UsersNewController.js, public/js/app/initializers/Session.js
...because session creation uses async IO. This may be implemented with Promises but I am not sure it will be better.
The proper way is making currentUser a Promise and waiting for it on all routes requiring a session. My Ember-Fu is not enough for that.
Fix #104.
=> Postpone transition to "Home" via a callback

public/js/app/controllers/TimelineCommentsController.js, public/js/app/controllers/TimelineDiscussionsController.js, public/js/app/controllers/TimelineHomeController.js, public/js/app/controllers/TimelineIndexController.js, public/js/app/controllers/TimelineLikesController.js, public/js/app/initializers/PubSub.js
=>     Do not add objects to computed properties

public/js/app/controllers/PostController.js, public/js/app/controllers/PostGenericController.js, public/js/app/controllers/TimelineCommentsController.js, public/js/app/controllers/TimelineDiscussionsController.js, public/js/app/controllers/TimelineGenericController.js, public/js/app/controllers/TimelineHomeController.js, public/js/app/controllers/TimelineIndexController.js, public/js/app/controllers/TimelineLikesController.js, public/js/app/controllers/TimelinePostController.js, public/js/app/main.js
* Add generic controller for timelines
* Add generic controller for posts
=> TimelineGenericController & PostGenericController

public/js/app/router.js
Implementation is trivial, copy-pasted from documentation and just works™
=> Enabled HTML5 History API in EmberJS app

themes/helvetica/post.scss
Quick and dirty solution for the excessive whitespace around commas in likes list.
=> Fix UI: Better styling for likes [Issue #288]

themes/shared/lists.scss
More robust grid and support for long displaynames.
Fixes #319
=> Fix layout for subscription/subscriber list

public/js/app/templates/postAttachmentTemplate.handlebars, public/js/libs/plugins/jquery.anchorlinks.js
=> Add target="_blank" to attachments and post links

public/js/app/templates/settingsFeedTemplate.handlebars, public/js/app/templates/settingsIndexTemplate.handlebars
=> Padding for profile picture input

public/js/app/templates/postTemplate.handlebars
Fixes #330.
This is a follow-up to #345.
=> Remove a bracket (hotfix)

themes/helvetica/header.scss
Aligns the page title ("Freefeed") with other elements on the page.
=> Add 10px margin to the header

.gitignore, Jakefile
=> CSS source maps

themes/helvetica/forms.scss
=> Prevent textareas from being resized horizontally too much [Issue #315]

public/js/app/templates/postTemplate.handlebars, public/js/app/templates/timelinePostTemplate.handlebars
=> Change "Destroy" links to "Delete" [Issue #126]

public/js/app/helpers/Handlebars.js, public/js/app/templates/postLikesTemplate.handlebars, themes/helvetica/post.scss
mixed css+templates solution instead of css-only
=> fix for hanging comma in likes usernames list

public/js/app/fields/EditPostView.js
easy fix: this was already done for comments but not for posts
=> focus post textarea on "Edit" action

public/index.html, public/js/app/app.js
=> Indicate process of app initialization

themes/helvetica/post.scss
test on post: https://micropeppa.freefeed.net/berkus/24f03122-9edd-4ff8-a400-50dfb63f5687
=> long names no longer slip down from the like-symbol, fixes #391

public/js/app/templates/timelinePostTemplate.handlebars, themes/shared/comments.scss
Added link "Add comment" below post comments in timeline. This fixes #369.
=> "Add comment" link after all comments

themes/fresh/post.scss, themes/helvetica/post.scss
=> Fix width of "Likes" list

public/js/app/fields/CreateAttachmentView.js
=> Enable multiple file upload for attachments
